// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"db/ent/predicate"
	"db/ent/tourproduct"
	"db/ent/user"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TourProductQuery is the builder for querying TourProduct entities.
type TourProductQuery struct {
	config
	limit       *int
	offset      *int
	unique      *bool
	order       []OrderFunc
	fields      []string
	predicates  []predicate.TourProduct
	withManager *UserQuery
	withFKs     bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TourProductQuery builder.
func (tpq *TourProductQuery) Where(ps ...predicate.TourProduct) *TourProductQuery {
	tpq.predicates = append(tpq.predicates, ps...)
	return tpq
}

// Limit adds a limit step to the query.
func (tpq *TourProductQuery) Limit(limit int) *TourProductQuery {
	tpq.limit = &limit
	return tpq
}

// Offset adds an offset step to the query.
func (tpq *TourProductQuery) Offset(offset int) *TourProductQuery {
	tpq.offset = &offset
	return tpq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tpq *TourProductQuery) Unique(unique bool) *TourProductQuery {
	tpq.unique = &unique
	return tpq
}

// Order adds an order step to the query.
func (tpq *TourProductQuery) Order(o ...OrderFunc) *TourProductQuery {
	tpq.order = append(tpq.order, o...)
	return tpq
}

// QueryManager chains the current query on the "manager" edge.
func (tpq *TourProductQuery) QueryManager() *UserQuery {
	query := &UserQuery{config: tpq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tpq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tourproduct.Table, tourproduct.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, tourproduct.ManagerTable, tourproduct.ManagerColumn),
		)
		fromU = sqlgraph.SetNeighbors(tpq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TourProduct entity from the query.
// Returns a *NotFoundError when no TourProduct was found.
func (tpq *TourProductQuery) First(ctx context.Context) (*TourProduct, error) {
	nodes, err := tpq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{tourproduct.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tpq *TourProductQuery) FirstX(ctx context.Context) *TourProduct {
	node, err := tpq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TourProduct ID from the query.
// Returns a *NotFoundError when no TourProduct ID was found.
func (tpq *TourProductQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tpq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{tourproduct.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tpq *TourProductQuery) FirstIDX(ctx context.Context) int {
	id, err := tpq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TourProduct entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TourProduct entity is found.
// Returns a *NotFoundError when no TourProduct entities are found.
func (tpq *TourProductQuery) Only(ctx context.Context) (*TourProduct, error) {
	nodes, err := tpq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{tourproduct.Label}
	default:
		return nil, &NotSingularError{tourproduct.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tpq *TourProductQuery) OnlyX(ctx context.Context) *TourProduct {
	node, err := tpq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TourProduct ID in the query.
// Returns a *NotSingularError when more than one TourProduct ID is found.
// Returns a *NotFoundError when no entities are found.
func (tpq *TourProductQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tpq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{tourproduct.Label}
	default:
		err = &NotSingularError{tourproduct.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tpq *TourProductQuery) OnlyIDX(ctx context.Context) int {
	id, err := tpq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TourProducts.
func (tpq *TourProductQuery) All(ctx context.Context) ([]*TourProduct, error) {
	if err := tpq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return tpq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (tpq *TourProductQuery) AllX(ctx context.Context) []*TourProduct {
	nodes, err := tpq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TourProduct IDs.
func (tpq *TourProductQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := tpq.Select(tourproduct.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tpq *TourProductQuery) IDsX(ctx context.Context) []int {
	ids, err := tpq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tpq *TourProductQuery) Count(ctx context.Context) (int, error) {
	if err := tpq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return tpq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (tpq *TourProductQuery) CountX(ctx context.Context) int {
	count, err := tpq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tpq *TourProductQuery) Exist(ctx context.Context) (bool, error) {
	if err := tpq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return tpq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (tpq *TourProductQuery) ExistX(ctx context.Context) bool {
	exist, err := tpq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TourProductQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tpq *TourProductQuery) Clone() *TourProductQuery {
	if tpq == nil {
		return nil
	}
	return &TourProductQuery{
		config:      tpq.config,
		limit:       tpq.limit,
		offset:      tpq.offset,
		order:       append([]OrderFunc{}, tpq.order...),
		predicates:  append([]predicate.TourProduct{}, tpq.predicates...),
		withManager: tpq.withManager.Clone(),
		// clone intermediate query.
		sql:    tpq.sql.Clone(),
		path:   tpq.path,
		unique: tpq.unique,
	}
}

// WithManager tells the query-builder to eager-load the nodes that are connected to
// the "manager" edge. The optional arguments are used to configure the query builder of the edge.
func (tpq *TourProductQuery) WithManager(opts ...func(*UserQuery)) *TourProductQuery {
	query := &UserQuery{config: tpq.config}
	for _, opt := range opts {
		opt(query)
	}
	tpq.withManager = query
	return tpq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TourProduct.Query().
//		GroupBy(tourproduct.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tpq *TourProductQuery) GroupBy(field string, fields ...string) *TourProductGroupBy {
	grbuild := &TourProductGroupBy{config: tpq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := tpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return tpq.sqlQuery(ctx), nil
	}
	grbuild.label = tourproduct.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.TourProduct.Query().
//		Select(tourproduct.FieldName).
//		Scan(ctx, &v)
func (tpq *TourProductQuery) Select(fields ...string) *TourProductSelect {
	tpq.fields = append(tpq.fields, fields...)
	selbuild := &TourProductSelect{TourProductQuery: tpq}
	selbuild.label = tourproduct.Label
	selbuild.flds, selbuild.scan = &tpq.fields, selbuild.Scan
	return selbuild
}

// Aggregate returns a TourProductSelect configured with the given aggregations.
func (tpq *TourProductQuery) Aggregate(fns ...AggregateFunc) *TourProductSelect {
	return tpq.Select().Aggregate(fns...)
}

func (tpq *TourProductQuery) prepareQuery(ctx context.Context) error {
	for _, f := range tpq.fields {
		if !tourproduct.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tpq.path != nil {
		prev, err := tpq.path(ctx)
		if err != nil {
			return err
		}
		tpq.sql = prev
	}
	return nil
}

func (tpq *TourProductQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TourProduct, error) {
	var (
		nodes       = []*TourProduct{}
		withFKs     = tpq.withFKs
		_spec       = tpq.querySpec()
		loadedTypes = [1]bool{
			tpq.withManager != nil,
		}
	)
	if tpq.withManager != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, tourproduct.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TourProduct).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TourProduct{config: tpq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tpq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := tpq.withManager; query != nil {
		if err := tpq.loadManager(ctx, query, nodes, nil,
			func(n *TourProduct, e *User) { n.Edges.Manager = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (tpq *TourProductQuery) loadManager(ctx context.Context, query *UserQuery, nodes []*TourProduct, init func(*TourProduct), assign func(*TourProduct, *User)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*TourProduct)
	for i := range nodes {
		if nodes[i].user_products == nil {
			continue
		}
		fk := *nodes[i].user_products
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_products" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (tpq *TourProductQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tpq.querySpec()
	_spec.Node.Columns = tpq.fields
	if len(tpq.fields) > 0 {
		_spec.Unique = tpq.unique != nil && *tpq.unique
	}
	return sqlgraph.CountNodes(ctx, tpq.driver, _spec)
}

func (tpq *TourProductQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := tpq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (tpq *TourProductQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   tourproduct.Table,
			Columns: tourproduct.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: tourproduct.FieldID,
			},
		},
		From:   tpq.sql,
		Unique: true,
	}
	if unique := tpq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := tpq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tourproduct.FieldID)
		for i := range fields {
			if fields[i] != tourproduct.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tpq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tpq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tpq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tpq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tpq *TourProductQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tpq.driver.Dialect())
	t1 := builder.Table(tourproduct.Table)
	columns := tpq.fields
	if len(columns) == 0 {
		columns = tourproduct.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tpq.sql != nil {
		selector = tpq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tpq.unique != nil && *tpq.unique {
		selector.Distinct()
	}
	for _, p := range tpq.predicates {
		p(selector)
	}
	for _, p := range tpq.order {
		p(selector)
	}
	if offset := tpq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tpq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TourProductGroupBy is the group-by builder for TourProduct entities.
type TourProductGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tpgb *TourProductGroupBy) Aggregate(fns ...AggregateFunc) *TourProductGroupBy {
	tpgb.fns = append(tpgb.fns, fns...)
	return tpgb
}

// Scan applies the group-by query and scans the result into the given value.
func (tpgb *TourProductGroupBy) Scan(ctx context.Context, v any) error {
	query, err := tpgb.path(ctx)
	if err != nil {
		return err
	}
	tpgb.sql = query
	return tpgb.sqlScan(ctx, v)
}

func (tpgb *TourProductGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range tpgb.fields {
		if !tourproduct.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := tpgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tpgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (tpgb *TourProductGroupBy) sqlQuery() *sql.Selector {
	selector := tpgb.sql.Select()
	aggregation := make([]string, 0, len(tpgb.fns))
	for _, fn := range tpgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(tpgb.fields)+len(tpgb.fns))
		for _, f := range tpgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(tpgb.fields...)...)
}

// TourProductSelect is the builder for selecting fields of TourProduct entities.
type TourProductSelect struct {
	*TourProductQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tps *TourProductSelect) Aggregate(fns ...AggregateFunc) *TourProductSelect {
	tps.fns = append(tps.fns, fns...)
	return tps
}

// Scan applies the selector query and scans the result into the given value.
func (tps *TourProductSelect) Scan(ctx context.Context, v any) error {
	if err := tps.prepareQuery(ctx); err != nil {
		return err
	}
	tps.sql = tps.TourProductQuery.sqlQuery(ctx)
	return tps.sqlScan(ctx, v)
}

func (tps *TourProductSelect) sqlScan(ctx context.Context, v any) error {
	aggregation := make([]string, 0, len(tps.fns))
	for _, fn := range tps.fns {
		aggregation = append(aggregation, fn(tps.sql))
	}
	switch n := len(*tps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		tps.sql.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		tps.sql.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := tps.sql.Query()
	if err := tps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
